### ISSUE TITLE
name of libs

### ISSUE THREAD

**Issue by sirAlexanderT** [qudini/qudini-reactive#23]
As these seem to be tied to spring and more specifically Springs reactive implementation 'io.reactor' i.e. 'Mono / Flux' should they be called 'qudini-reactor' ?  as they possibly won't work with other reactive implementations. @sp00m Thoughts?

**Comment by sp00m** [comment]
Hmm, good point! Not sure if worth the hassle though, "qudini-reactive" is everywhere already I'm afraid :/ I mean, inside the code itself, the repo name, the end package name... I'm probably missing some.
