### ISSUE TITLE
Can we align the structured logs fields with ECS 

### ISSUE THREAD

**Issue by mohsen0** [qudini/qudini-reactive#66]
https://www.elastic.co/guide/en/ecs/current/ecs-getting-started.html

**Comment by sp00m** [comment]
Do you mean these fields: https://github.com/qudini/qudini-reactive/tree/master/qudini-reactive-logging#json-structured-logging? If yes, what makes then not aligned with ECS exactly?

**Comment by mohsen0** [comment]
sorry the link has changed https://www.elastic.co/guide/en/ecs/1.12/index.html
The field names do not match with ECS but Let's hold off on this one since I am not sure about that anymore
